❌ Missing db method get_undownloaded_urls
ice_entitlement_using_node_js
Traceback (most recent call last):
  File "/Users/laptop/Development/01-Learning/oai/openai-cookbook/apps/web-crawl-q-and-a/PROMPTING/download code and related wwdc session/get_wwdc_docs_code_and_post.py", line 205, in <module>
    main()
  File "/Users/laptop/Development/01-Learning/oai/openai-cookbook/apps/web-crawl-q-and-a/PROMPTING/download code and related wwdc session/get_wwdc_docs_code_and_post.py", line 201, in main
    process_view_code_urls(driver, db)
  File "/Users/laptop/Development/01-Learning/oai/openai-cookbook/apps/web-crawl-q-and-a/PROMPTING/download code and related wwdc session/get_wwdc_docs_code_and_post.py", line 183, in process_view_code_urls
    urls_to_process = db.get_undownloaded_urls()
AttributeError: 'WWDCDatabase' object has no attribute 'get_undownloaded_urls'